### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Olliecad1**

### CODE REVIEW

**Comment by MrChrisJ** [comment]
Cool thanks. I am gonna test these first and then merge them. Thanks for your work Ollie, it looks great.

**Comment by MrChrisJ** [comment]
Just found an error on line 4 which was truncating some dependencies. I have now fixed and am testing again. I will report back when it's done in a few hours.

**Comment by ghost** [comment]
i tried the lower half of it earlier today - skipped the bitcoin install bit and ran the electrum and btchip part .. and although it ran there was no electrum icon in desktop menu - so it needs work.  Its probably bettter to install with pip as per electrum.org ... also the btchip stuff did not seem to work - i tried loading a ledger wallet with electrum but got errors and reported them to Ollie

**Comment by Olliecad1** [comment]
oh you got some errors

**Comment by Olliecad1** [comment]
i didn't comment who did this ?

**Comment by TechStuffPGP** [comment]
Not me

**Comment by Olliecad1** [comment]
sorry yes i did write this lol i thought it was the 23rd of march but its 23rd of april 2016 lol

**Pull request merged**
