### PR TITLE
extract scripts and template from setup.md

### PR DESCRIPTION
**Pull request by ralphtheninja**
@MrChrisJ This is the initial version.

The diff of `setup.md` looks a bit messy, but I have essentially extracted all of the commands into the `bitcoin/install` script and deleted the instructions from `setup.md` (since they have been abstracted by the scripts and also documented inside the scripts).

I've tried to comment the scripts properly. I normally don't comment as much, but I think it's good if we try to be overly clear about things.

Closes https://github.com/MrChrisJ/fullnode/issues/15

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@MrChrisJ Gonna test this on my own RPI2. Hold off with merge until I know that works well.

**Comment by ralphtheninja** [comment]
@MrChrisJ Can we merge this? Or anything you're not happy with? I'm also part of the adhd generation so I have no patience ;)

**Comment by MrChrisJ** [comment]
Ah sorry this conflicted with the update I just did, I moved it to here: https://github.com/MrChrisJ/fullnode/tree/master/Setup_Guides

**Comment by ralphtheninja** [comment]
I'll come back with an update PR later :)

**Pull request closed without merging**
